### PR TITLE
Add MCC/MNC outputs

### PR DESCRIPTION
**Pull request by horgh**
These are upcoming outputs that we're preparing for. You can see another PR I worked on for our Ruby library as a reference if that would be useful: https://github.com/maxmind/GeoIP2-ruby/pull/38/commits/ef71b425a2cbbd77624a0ef25ce3db53953e7eba.

If possible, I'd love a release that I could use with node-maxmind!

Thank you!

### CODE REVIEW

**Comment by horgh** [comment]
Hi! Sorry to bother, but I just wanted to follow up to see if you'd be able to look at this at some point. Thank you!

**Comment by horgh** [comment]
Hi again. I thought I'd ping one more time to see if we could get this merged! Thanks again!

**Review by runk — APPROVED** [review]

**Comment by runk** [comment]
Sorry just noticed your pull request 🤕

**Comment by horgh** [comment]
All good. Thank you!

**Pull request merged**
